import { IoChevronDown } from "react-icons/io5";

const faqs = [
  {
    question: "What is the referral rebate?",
    answer:
      "A referral rebate is a reward you earn when users you refer generate activity on the platform.",
  },
  {
    question: "How is my rebate calculated?",
    answer:
      "Your rebate is calculated as a percentage of the fees generated by your referrals.",
  },
  {
    question: "When can I claim my rebate?",
    answer:
      "Rebates can be claimed once they meet the minimum withdrawal threshold.",
  },
  {
    question: "Can I change my referrer?",
    answer: "No, once a referrer is set it cannot be changed.",
  },
];

export default function FaqsComponent() {
  return (
    <section className="w-full">
      <h2 className="font-manrope mb-2 text-sm md:text-base font-semibold text-white/90">
        Frequently Asked Questions (FAQs)
      </h2>

      <div className="space-y-1 md:space-y-2">
        {faqs.map((faq, i) => (
          <details
            key={i}
            className="group rounded-xl bg-[#121712] border border-white/5 px-4 py-3"
          >
            <summary
              className="flex cursor-pointer items-center justify-between list-none font-manrope text-sm md:text-base text-[#B5B5B5]
              "
            >
              {faq.question}

              <span
                className="ml-2 text-white transition-transform duration-200 group-open:rotate-180"
              >
                <IoChevronDown size={18} />
              </span>
            </summary>

            <div className="mt-3 text-sm md:text-base text-[#B5B5B5] leading-relaxed">
              {faq.answer}
            </div>
          </details>
        ))}
      </div>
    </section>
  );
}

